### ISSUE TITLE
文件分片和断点续传有吗？

### ISSUE THREAD

**Issue by xiao8Git** [dromara/x-file-storage#100]
文件分片和断点续传有实现吗？

**Comment by 1171736840** [comment]
大文件自动分片上传，下班版本将增加手动分片上传，断点续传目前没有好的办法全平台实现，等以后有办法了再说吧

**Comment by arden-yang** [comment]
大文件多线程分片下载，断点续传下个版本有考虑吗

**Comment by 1171736840** [comment]
多线程下载暂时没有好的方案兼容多个平台，
大文件手动分片按顺序排队上传已经有方案兼容全平台了，下个版本会实现

**Comment by arden-yang** [comment]
目前支持FastDFS不

**Comment by 1171736840** [comment]
不支持

**Comment by 1171736840** [comment]
目前2.1.0版本已支持此功能， [点击查看详情](https://x-file-storage.xuyanwu.cn/#/%E5%9F%BA%E7%A1%80%E5%8A%9F%E8%83%BD?id=%e6%89%8b%e5%8a%a8%e5%88%86%e7%89%87%e4%b8%8a%e4%bc%a0)

**Comment by 1171736840** [comment]
> 目前支持FastDFS不

目前2.1.0版本已支持此功能， [点击查看详情](https://x-file-storage.xuyanwu.cn/#/%E5%AD%98%E5%82%A8%E5%B9%B3%E5%8F%B0?id=%e6%94%af%e6%8c%81%e7%9a%84%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0)
