### ISSUE TITLE
可以支持或自定义扩展对象存储其他功能吗，比如copy ?

### ISSUE THREAD

**Issue by wonvee** [dromara/x-file-storage#103]
期望支持或者自定义扩展 copy 能力

S3：https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html

华为OBS：https://support.huaweicloud.com/api-obs/obs_04_0082.html

**Comment by 1171736840** [comment]
这个公共可以参考 [自定义存储平台](https://spring-file-storage.xuyanwu.cn/#/存储平台?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0) 来实现，或者获取到对应平台的 Client 对象手动操作

**Comment by 1171736840** [comment]
目前已实现文件的复制和移动功能，下个版本将会正式发布，目前已提交到dev分支并发布镜像版本，感兴趣可以先试用
```xml
<dependency>
    <groupId>org.dromara.x-file-storage</groupId>
    <artifactId>x-file-storage-spring</artifactId>
    <version>2.1.0-SNAPSHOT</version>
</dependency>
```

![image](https://github.com/dromara/x-file-storage/assets/35297205/5d412f4e-1c15-4f38-a48f-aff26671f9fc)
![image](https://github.com/dromara/x-file-storage/assets/35297205/cd6c103c-e879-4ba6-bebe-9f1803ea57b9)
![577DSE2 U{M6U7@RDI$J31Q](https://github.com/dromara/x-file-storage/assets/35297205/9c188800-5916-4964-acd4-15d0a5db7e40)
![15I}N9QB3`$FSB %3PC{_$1](https://github.com/dromara/x-file-storage/assets/35297205/ff79d967-ed07-4087-9fee-3b2dcd721812)

**Comment by 1171736840** [comment]
目前2.1.0版本已支持此功能， [点击查看详情](https://x-file-storage.xuyanwu.cn/#/%E5%9F%BA%E7%A1%80%E5%8A%9F%E8%83%BD?id=%e5%a4%8d%e5%88%b6)
