### ISSUE TITLE
spring-boot-devtools 自动重启报错

### ISSUE THREAD

**Issue by marlboro029** [dromara/x-file-storage#117]
spring-boot：2.7.16
spring-file-storage：1.0.3
报错信息：
<img width="1567" alt="image" src="https://github.com/dromara/x-file-storage/assets/1843098/716f0ac2-f3d9-417e-80e0-84ffa8c8b94c">
代码：
<img width="1051" alt="image" src="https://github.com/dromara/x-file-storage/assets/1843098/4890b29f-eb99-4318-88d6-bf29d6d9ba90">

**Comment by 1171736840** [comment]
这个是不是你在修改了 SysFileServiceImpl 之后自动重启报错的？

**Comment by marlboro029** [comment]
是的。

**Comment by 1171736840** [comment]
这部分通过@ConditionalOnMissingBean初始化的，可能有些不兼容吧

**Comment by 1171736840** [comment]
这种情况先把自动重启关了，等这部分逻辑写好后再开启自动重启，按理说这部分代码写好后也不会频繁修改，影响不会很大
