### ISSUE TITLE
请问现在支持分块上传吗？

### ISSUE THREAD

**Issue by ZeroNing** [dromara/x-file-storage#119]

**Comment by 1171736840** [comment]
暂时不支持手动分块上传，后续会支持，目前上传大文件时会自动处理，和上传小文件一样操作就好

**Comment by 1171736840** [comment]
目前2.1.0版本已支持此功能， [点击查看详情](https://x-file-storage.xuyanwu.cn/#/%E5%9F%BA%E7%A1%80%E5%8A%9F%E8%83%BD?id=%e6%89%8b%e5%8a%a8%e5%88%86%e7%89%87%e4%b8%8a%e4%bc%a0)
