### ISSUE TITLE
是否有对 azure blob 的支持计划

### ISSUE THREAD

**Issue by fxbin** [dromara/x-file-storage#161]
是否有对 azure blob 的支持计划？
如果有的话我也可以贡献关于这部分的实现

**Comment by 1171736840** [comment]
前几天群内有个成员说要提交 AzureBlob 相关代码，但是目前还没有提交，可以加QQ群交流一下：515706495

**Comment by fxbin** [comment]
> 前几天群内有个成员说要提交 AzureBlob 相关代码，但是目前还没有提交，可以加QQ群交流一下：515706495

OK

**Comment by 1171736840** [comment]
目前2.1.0版本已支持此功能， [点击查看详情](https://x-file-storage.xuyanwu.cn/#/%E5%AD%98%E5%82%A8%E5%B9%B3%E5%8F%B0?id=%e6%94%af%e6%8c%81%e7%9a%84%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0)
