### ISSUE TITLE
有计划剔除掉Hutool框架么

### ISSUE THREAD

**Issue by dute7liang** [dromara/x-file-storage#175]
虽然HuTool框架挺好用，但是HuTool的版本对API的改动影响太大。规范不大好。

第三方框架只要互相用了不兼容的HuTool版本API。都是头疼了

![微信图片_20231207185049](https://github.com/dromara/x-file-storage/assets/31098086/6d5fca74-da37-40aa-b99e-208f77f3a0a8)

**Comment by dute7liang** [comment]
已经被次问题折磨了太多。

**Comment by 1171736840** [comment]
自己实现相关工具类的话工作量较大，暂时不在计划内，以后功能开发的差不多了会考虑

**Comment by 1171736840** [comment]
你看尝试手动引用一个 hutool 版本，看看能不能找到两边都兼容的版本

**Comment by 1171736840** [comment]
实在不行还可以手动拉取此项目源码，找到冲突部分改掉后，自行编译使用

**Comment by dute7liang** [comment]
嗯，行吧。我想的用标准的Apache工具类，API会稳定很多。 感谢答复
