### ISSUE TITLE
文件下载提示：尚未实现 FileRecorder 接口，暂时无法使用此功能

### ISSUE THREAD

**Issue by zhangzimuzjq** [dromara/x-file-storage#187]
我现在是能上传文件到minio，但是通过文件路径下载的时候提示：尚未实现 FileRecorder 接口。这个是要自己去实现嘛？

还有我使用fileInfo 去下载也是一样的提示。
FileInfo fileInfo = fileStorageService.getFileInfoByUrl(fileUrl);

![Dingtalk_20240102115240](https://github.com/dromara/x-file-storage/assets/30472775/c1e001b3-c326-4391-87a0-84fb557afed2)

**Comment by 1171736840** [comment]
看一下文档快速入门最后面，有相关说明

**Comment by zhangzimuzjq** [comment]
好的 阔以了
