### ISSUE TITLE
download方法只能下载通过FileRecorder存入数据库中的文件吗

### ISSUE THREAD

**Issue by wandoupeas** [dromara/x-file-storage#221]
实现了FileRecorder，download传入url后会执行getByUrl方法，此方法官方示例为从数据库中获取url相关的文件，实际场景中需要从外部链接（如oss等）下载文件，这是需要自己实现吗

**Comment by 1171736840** [comment]
这个功能目前在dev分支已经完成，可以等下个正式版，或拉取dev分支自行编译，也可以获取对应的存储平台再 getClient 后自行操作

**Comment by 1171736840** [comment]
如果你指的是上传的不是本地文件，而是一个链接，可以这样上传 fileStorageService.of("https://abc.com/a.jpg").upload()

**Comment by wandoupeas** [comment]
> 这个功能目前在dev分支已经完成，可以等下个正式版，或拉取dev分支自行编译，也可以获取对应的存储平台再 getClient 后自行操作
食用方式跟原来一致吗

**Comment by 1171736840** [comment]
> > 这个功能目前在dev分支已经完成，可以等下个正式版，或拉取dev分支自行编译，也可以获取对应的存储平台再 getClient 后自行操作
> 
> 食用方式跟原来一致吗

你可以试试

**Comment by xieTaka** [comment]
> 或许你还可以参考快速入门最后面那部分手动构造FileInfo对象进行使用

可以告诉一下，FileInfo对象中，哪些是OSS下载的时候，必须的属性吗？，我这边也是不需要存进数据库的
