### ISSUE TITLE
上传文件返回的URL中没有bucket路径

### ISSUE THREAD

**Issue by satan12345** [dromara/x-file-storage#222]
上传文件成功的路径中没有包含bucket，虽然是可以把bucket添加到domain中解决这个，获取拿到URL进行重新拼接。但是这样总感觉不太方便。,也看到有人提过issues，但是一直没改 ，是有什么顾虑 还是有其他原因
![A{YOKA{HPTVN)11T4 )MP9Y](https://github.com/dromara/x-file-storage/assets/20388252/3184bff7-5c5f-400f-80ac-fa17f098bf88)

**Comment by 1171736840** [comment]
bucket 属于存储平台相关数据，暂时没什么用，有需要可以获取到对应存储平台，然后再获取 bucket ，可以在切面中统一处理，保存的 FileInfo 的 att 参数中

**Comment by satan12345** [comment]
这个框架的意义不就是屏蔽底层不同OSS，比如腾讯云在文件上传后文件的URL中不会包含bucket路径,而minio则需要包含bucketName才可以访问，如果在FileStorage的子类的save方法中进行对不同的OSS进行不同的处理 是不是会更好一些

**Comment by 1171736840** [comment]
如果是因为访问需要bucket，那直接配置在 bucket 就行了，目前只有MinIO访问需要带 bucket

**Comment by 1171736840** [comment]
至于你说的其它的，我不是很理解
