### ISSUE TITLE
前端获取大文件上传进度

### ISSUE THREAD

**Issue by zhangzimuzjq** [dromara/x-file-storage#223]
需要上传的文件有好几G，前端要咋获取实时的上传进度啊。
是在setProgressListener里面存Redis后前端轮询，还是有其他更好的方式啊。

**Comment by 1171736840** [comment]
是的，也可以基于 HttpServletRequest 上传，这样前端的上传进度约等于后端上传进度，使用方式见官网文档

**Comment by zhangzimuzjq** [comment]
我用HttpServletRequest 方式上传，文件能上传成功，但是获取不到请求中的参数。apifox和postman一样的。
![image](https://github.com/dromara/x-file-storage/assets/30472775/cec0a00b-d1cd-464b-8464-f028d0bf2b7e)
![image](https://github.com/dromara/x-file-storage/assets/30472775/a083f953-2737-493c-8fe5-7a2b36ba526b)

**Comment by 1171736840** [comment]
注意看文档，是参数顺序问题，文件必须是最后一个参数

**Comment by 1171736840** [comment]
如果文件过多，也可以考虑使用手动分片上传，就是用起来麻烦，没有这种直接上传简单

**Comment by zhangzimuzjq** [comment]
好的  我以为那是客户端才要这种传
