### ISSUE TITLE
请问为什么静态资源处理器fileStorageWebMvcConfigurer不起作用呢？

### ISSUE THREAD

**Issue by StudyofNeural** [dromara/x-file-storage#229]
### 当我配置成local-plus的存储引擎的时候，静态资源无法直接访问

**Comment by StudyofNeural** [comment]
![image](https://github.com/dromara/x-file-storage/assets/20700731/c6f67095-3cd8-482b-89ad-c0ce067de39f)

**Comment by StudyofNeural** [comment]
![image](https://github.com/dromara/x-file-storage/assets/20700731/ab9cd8b1-988d-401e-ae19-8fd43d65c140)

**Comment by StudyofNeural** [comment]
我尝试自己手写了一个类，实现WebMvcConfigurer接口是可行的：
![image](https://github.com/dromara/x-file-storage/assets/20700731/7e4b7a39-d1cc-4807-87a9-d24d5764a1f9)

**Comment by 1171736840** [comment]
你在自带的 WebMvcConfigurer 接口中打个断点看看，有没有正常执行

**Comment by StudyofNeural** [comment]
我试过，能进去new 对象，但是add方法没进去。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月7日(周四) 中午11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dromara/x-file-storage] 请问为什么静态资源处理器fileStorageWebMvcConfigurer不起作用呢？ (Issue #229)




 
你在自带的 WebMvcConfigurer 接口中打个断点看看，有没有正常执行

**Comment by 1171736840** [comment]
你用的springboot版本多少

**Comment by StudyofNeural** [comment]
2.3.2.RELEASE

**Comment by 1171736840** [comment]
要不你尝试换个springboot版本试试？要还是不行就先这样用吧

**Comment by StudyofNeural** [comment]
好的，谢谢。我自己再研究一下。

**Comment by StudyofNeural** [comment]
我做了以下改动，测试可行：
1. 启动类中排除FileStorageAutoConfiguration：
@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, classes = {FileStorageAutoConfiguration.class})
2. 自己实现FileStorageAutoConfiguration，去掉WebMvcConfigurer的配置。
3. 实现自己的CustomFileStorageWebMvcConfigurer，通过implements WebMvcConfigurer。
![image](https://github.com/dromara/x-file-storage/assets/20700731/1f26ddbf-8c44-4285-ac5b-c6e2659ffd4b)

后面有空再来研究是不是SpringBoot的版本。

**Comment by StudyofNeural** [comment]
@Bean
    @ConditionalOnClass(name = "org.springframework.web.servlet.config.annotation.WebMvcConfigurer")
    public ```WebMvcConfigurer``` fileStorageWebMvcConfigurer() {
        return new WebMvcConfigurer() {
            @Override
            public void addResourceHandlers(@NonNull ResourceHandlerRegistry registry) {
                for (SpringLocalConfig local : properties.getLocal()) {
                    if (local.getEnableStorage() && local.getEnableAccess()) {
                        registry.addResourceHandler(local.getPathPatterns())
                                .addResourceLocations("file:" + local.getBasePath());
                    }
                }
                for (SpringLocalPlusConfig local : properties.getLocalPlus()) {
                    if (local.getEnableStorage() && local.getEnableAccess()) {
                        registry.addResourceHandler(local.getPathPatterns())
                                .addResourceLocations("file:" + local.getStoragePath());
                    }
                }
            }
        };
    }

**Comment by 1171736840** [comment]
但是这在非 SpringWeb 环境下，没有 WebMvcConfigurer 这个类，可能会启动不了，具体我没试

**Comment by StudyofNeural** [comment]
返回值是Object：当一个配置类的某个方法返回Object类型时，它通常表示这个方法是提供一个普通的Java对象，这个对象可能被用于应用程序中的其他部分，但它并不直接参与Spring MVC的配置过程。
返回值是WebMvcConfigurer：当一个配置类的方法返回WebMvcConfigurer类型时，它表示这个方法是在提供Spring MVC配置的自定义实现。WebMvcConfigurer是一个接口，它定义了一组可以重写的方法，用于定制Spring MVC的行为，如视图解析、静态资源处理、拦截器等。通过实现WebMvcConfigurer接口并返回一个实例，开发者可以对这些特性进行详细的配置。

**Comment by StudyofNeural** [comment]
但是你这里return new  WebMvcConfigurer(){}也会报class not found吧？

**Comment by 1171736840** [comment]
@ConditionalOnClass(name = "org.springframework.web.servlet.config.annotation.WebMvcConfigurer")
用了这个判断，这部分等我有空处理一下，预计发布下个版本时会解决

**Comment by StudyofNeural** [comment]
对，这里的判断有了，说明WebMvcConfigurer已经存在了，所以返回WebMvcConfigurer也没毛病吧？

**Comment by 1171736840** [comment]
具体等我有空试一下

**Comment by 1171736840** [comment]
2.2.0版本已修复此问题，详情查看 [更新记录](https://x-file-storage.xuyanwu.cn/#/%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)
