### ISSUE TITLE
是否支持批量上传

### ISSUE THREAD

**Issue by rowstop** [dromara/x-file-storage#231]
RT

**Comment by 1171736840** [comment]
不支持，可以自行使用循环

**Comment by rowstop** [comment]
> 不支持，可以自行使用循环

考虑支持吗

**Comment by 1171736840** [comment]
> > 不支持，可以自行使用循环
> 
> 考虑支持吗

暂不考虑，我觉得没必要，一般写个循环就行了，多线程并行上传的话用 Stream 的 parallel() 方法就行了
