### ISSUE TITLE
Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.dromara.x.file.storage.core.FileStorageService.of(Ljava/lang/Object;)Lorg/dromara/x/file/storage/core/UploadPretreatment

### ISSUE THREAD

**Issue by 1343228975** [dromara/x-file-storage#233]
上传图片报错
Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.dromara.x.file.storage.core.FileStorageService.of(Ljava/lang/Object;)Lorg/dromara/x/file/storage/core/UploadPretreatment
代码：
   public FileInfo uploadImage(MultipartFile file,String imgPath,String type) {
        FileStorage fileStorage = fileStorageService.getFileStorage();
        String path = StringUtils.isEmpty(imgPath)? "image/": imgPath+"/"+ DateUtils.datePath() + "/";
        FileInfo fileInfo = fileStorageService.of(file)
                .setAcl(Constant.ACL.PRIVATE)
                .setOriginalFilename("a.jpg")
                .setObjectId("0")
                //关联对象类型，为了方便管理，不需要可以不写
                .setObjectType(ImgTypeEnum.YHY_AI_COVER.name())
                //保存一些属性，可以在切面、保存上传记录、自定义存储平台等地方获取使用，不需要可以不写
                .putAttr("role", "admin")
                //使用指定的存储平台
                .setPlatform("amazon-s3-1")
                        .upload();
        fileStorageService.setFileAcl(fileInfo, Constant.ACL.PUBLIC_READ);
        fileStorageService.setThFileAcl(fileInfo, Constant.ACL.PUBLIC_READ);
        return fileInfo;
    }
    版本：2.1.0

**Comment by 1171736840** [comment]
提示 NoSuchMethodError ，可能是第三方依赖冲突导致的，例如 AmazonS3 依赖的 okhttp 版本与已有的不兼容，你重新引入一个试试
