### ISSUE TITLE
升级 hutool 版本

### ISSUE THREAD

**Issue by cn-src** [dromara/x-file-storage#235]
<img width="1128" alt="image" src="https://github.com/dromara/x-file-storage/assets/8263180/f595f196-1066-4ff7-86af-2e1ff099d761">

**Comment by 1171736840** [comment]
等下个版本，你现在可以手动排除旧依赖，引入新依赖

**Comment by 1171736840** [comment]
2.2.0版本已升级 hutool 版本，详情查看 [更新记录](https://x-file-storage.xuyanwu.cn/#/%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)
