### ISSUE TITLE
分片上传数据失败

### ISSUE THREAD

**Issue by guai-shou** [dromara/x-file-storage#239]
x-file-storage版本2.1.0

想请教一下这个问题。
这里对数据源进行PartSource封装。
![image](https://github.com/dromara/x-file-storage/assets/54432459/02a35d31-cca9-4dae-a3c3-ca729d3071ba)
后续这里对数据源进行判断报错。导致上传失败
![image](https://github.com/dromara/x-file-storage/assets/54432459/5384a5a3-a23a-49d2-87aa-0755380739d0)

**Comment by 1171736840** [comment]
因为当时疏忽没注意到有两个同名方法，使用时有时会调用第一个，有时会调用第二个，下个版本会解决，目前可以参考：https://gitee.com/dromara/x-file-storage/issues/I9H2IB

**Comment by 1171736840** [comment]
2.2.0版本已修复此问题，详情查看 [更新记录](https://x-file-storage.xuyanwu.cn/#/%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)
