### ISSUE TITLE
建议支持预签名上传文件的功能

### ISSUE THREAD

**Issue by biluping** [dromara/x-file-storage#243]
minio 预签名上传地址后，文件可以在前端直接上传到minio这种平台
<img width="764" alt="image" src="https://github.com/dromara/x-file-storage/assets/49895589/064928b7-a05c-4b7d-9454-6053c7c191da">

**Comment by 1171736840** [comment]
你的建议非常好，目前dev分支已经支持，着急可以自行编译使用，或等后续发布正式版

**Comment by biluping** [comment]
ok，谢谢

**Comment by 1171736840** [comment]
2.2.0版本已支持此功能，详情查看 [更新记录](https://x-file-storage.xuyanwu.cn/#/%E6%9B%B4%E6%96%B0%E8%AE%B0%E5%BD%95)
