### ISSUE TITLE
xfileStorage实现分片下载的疑问

### ISSUE THREAD

**Issue by DoNotBugPlz** [dromara/x-file-storage#267]
支持有一个场景需要 ios 的视频播放需要，ios 视频播放默认分片下载
我这里需要 response 里的Last_Modified和ETag 字段，fileInfo 里好像获取不到这个信息，请问是否有示例？

**Comment by 1171736840** [comment]
如果是对象存储，分片可以使用预签名url，这个url是支持http分片的，直接丢给播放器就行了
要是本地存储之类的，可以参考获取文件这个文档

**Comment by DoNotBugPlz** [comment]
> 如果是对象存储，分片可以使用预签名url，这个url是支持http分片的，直接丢给播放器就行了 要是本地存储之类的，可以参考获取文件这个文档
谢谢，不过业务上没有办法返回 url，只能写在 response 里或者返回 byte[]～
