### ISSUE TITLE
支持通过文件的摘要信息秒传文件

### ISSUE THREAD

**Issue by ion1ze** [dromara/x-file-storage#268]
判断是否存在能否加上使用摘要信息判断的比如 md5，可以少些一些逻辑

**Comment by 1171736840** [comment]
那你可以通过获取文件的方式来判断，[文档](https://x-file-storage.xuyanwu.cn/#/%E5%9F%BA%E7%A1%80%E5%8A%9F%E8%83%BD?id=%e8%8e%b7%e5%8f%96%e6%96%87%e4%bb%b6)

**Comment by 1171736840** [comment]
如果是为了实现秒传，你可以在上传时计算MD5后保存到数据库，再次上传时客户端计算MD5和数据库中的数据进行对比，参考：[计算哈希](https://x-file-storage.xuyanwu.cn/#/hash)

**Comment by ion1ze** [comment]
所以还是得手动，就是想后续能不能扩展那个 exist 方法，哈哈哈 😆
