### ISSUE TITLE
文件列举是否支持或者计划支持分页查询呢

### ISSUE THREAD

**Issue by lax0306** [dromara/x-file-storage#274]
如题：文件列举是否支持或者计划支持分页查询呢
文件夹中如果文件数量过多，渲染给前端后会出现前端系统崩溃，所以是否支持分页查询呢

**Comment by 1171736840** [comment]
当然支付分页查询了，自己查看相关参数即可，操作方式与S3一致，为了减少使用麻烦，默认查询全部的

**Comment by lax0306** [comment]
好的  谢谢 只是浏览了下大致功能 还没有看具体的代码实现  感谢  很棒的项目
