### ISSUE TITLE
感谢对 solon 的支持！！！

### ISSUE THREAD

**Issue by noear** [dromara/x-file-storage#280]
在 readme 的里，也可以给 solon 版些展示的机会：）

**Comment by 1171736840** [comment]
我对 solon 还不是太熟悉，后续会增加的，另外 solon 的 QQ 群加了几次进不去

**Comment by noear** [comment]
不会吧？进不群。。。是被拒了？还是被T了？。。。最近有些人进来打色情广告。管理比较严（要正确回答问题，才能进）

**Comment by 1171736840** [comment]
就是申请了，没有任何回应

**Comment by noear** [comment]
@1171736840 你填写的答案是什么？

**Comment by 1171736840** [comment]
java 框架，要不我再申请一下吧

**Comment by noear** [comment]
java 框架能进的。。。再试下

**Comment by 1171736840** [comment]
成功进入了！！！

**Comment by transtone** [comment]
@noear solon-2.9.3 跑不起来。https://github.com/dromara/x-file-storage/issues/297

**Comment by noear** [comment]
@transtone 有可能使用了弃用接口，在 2.9.3 里被移掉了（看看有什么提示）

**Comment by transtone** [comment]
```
Caused by: java.lang.invoke.LambdaConversionException:
 Invalid receiver type class org.noear.solon.core.handle.UploadedFile; 
not a subtype of implementation receiver type class org.noear.solon.core.handle.DownloadedFile
```

测试项目地址：https://gitee.com/gridsoft/x-file-storage-solon-test

ps: 
minio-solon-cloud-plugin 也不知道怎么用。示例居然是自创一个 media 文件，我只是想把 UploadFile 文件 put 上去而已！看了源码才知道 Media 是一个自建类型，可怎么样把 UploadFile 转 Media，还要摸索。可这不就是文档里加一句话的事吗？

**Comment by noear** [comment]
@transtone 完整的异常栈放出来看下。
