### ISSUE TITLE
阿里云预签名URL无法使用自定义域名

### ISSUE THREAD

**Issue by veapon** [dromara/x-file-storage#281]
原因是 org.dromara.x.file.storage.core.platform.AliyunOssFileStorageClientFactory#getClient 生成 OSSClient 时，客户端配置的 supportCname 属性被设置成 false 了，见：com.aliyun.oss.ClientBuilderConfiguration#ClientBuilderConfiguration。
按官方文档（https://help.aliyun.com/zh/oss/developer-reference/initialization-3?spm=a2c4g.11186623.0.0.5d6797f0u3jdVT），可以传一个自定义的配置进去，不知大佬是否考虑实现。

**Comment by 1171736840** [comment]
现在可以生成URL后做一个替换域名的操作就行了，后面会考虑加上这个功能

**Comment by 1171736840** [comment]
也可以通过自定义存储平台 Client 工厂来实现 [文档](https://x-file-storage.xuyanwu.cn/#/%E5%AD%98%E5%82%A8%E5%B9%B3%E5%8F%B0?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0-client-%e5%b7%a5%e5%8e%82)

**Comment by veapon** [comment]
> 也可以通过自定义存储平台 Client 工厂来实现 [文档](https://x-file-storage.xuyanwu.cn/#/%E5%AD%98%E5%82%A8%E5%B9%B3%E5%8F%B0?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e5%ad%98%e5%82%a8%e5%b9%b3%e5%8f%b0-client-%e5%b7%a5%e5%8e%82)

Soga, 谢谢～
