### ISSUE TITLE
[提问]可以修改自带的表结构吗

### ISSUE THREAD

**Issue by retroxz** [dromara/x-file-storage#290]
如题 项目中已经有了保存文件的表
现在想用x-storage开发多oss存储功能
请问自带的表结构可以改吗
所有字段都是必须的吗

还想请问一下 使用注入配置对象的方式
可能动态修改目前所用到的储存引擎类型吗 
例如 在不停机的情况下修改本地储存引擎为阿里云oss

**Comment by 1171736840** [comment]
这个可以根据需求自行调整
