### ISSUE TITLE
分片完成之后文件没有设置hash，只有在分片数据上可以设置hash

### ISSUE THREAD

**Issue by liguochuan00** [dromara/x-file-storage#291]
![image](https://github.com/user-attachments/assets/5ce94157-c297-4a2b-8062-025e5010e8b4)
![image](https://github.com/user-attachments/assets/9a2e04ea-014f-4ac3-a758-13b675f5286e)

**Comment by 1171736840** [comment]
是的，目前是这样，因为计算 hash 需要按顺序把文件全部读取一遍进行计算，目前无法实现这个功能，有需要可以使用下载方法自行计算
