### ISSUE TITLE
webdav怎么配置alist

### ISSUE THREAD

**Issue by yuzhi-jiang** [dromara/x-file-storage#84]
如题，配置了好几次，都上传不成功,
![image](https://github.com/1171736840/spring-file-storage/assets/45190043/360ce476-e181-4073-b68b-c9315e0b28c9)

报错如下
![image](https://github.com/1171736840/spring-file-storage/assets/45190043/fe2cc33d-2e93-4595-837f-3ae797f0f724)

**Comment by yuzhi-jiang** [comment]
这个是配置问题，还是alist或者webdav的问题？

**Comment by 1171736840** [comment]
不知道，可以先自行使用第三方webdav客户端进行连接上传试试

**Comment by yuzhi-jiang** [comment]
好的

**Comment by yuzhi-jiang** [comment]
还有个问题，作者大大，存储路径可以理解，这个基础路径指的是什么，是必填的吗

**Comment by 1171736840** [comment]
是的你可以先照着文档写一个试一下，就知道什么意思了

**Comment by yuzhi-jiang** [comment]
好的，研究了下，可以使用了，确实是因为这个基础路径的含义不明确导致的

**Comment by ziwindlu** [comment]
> 好的，研究了下，可以使用了，确实是因为这个基础路径的含义不明确导致的

请问你是怎么配置的，我的alist挂载了阿里网盘，虽然请求不报错但是上传有问题，文件并未正常上传，下面是我的配置文件

```
      - platform: webdav-2 # 存储平台标识
        enable-storage: true  # 启用存储
        server: http://192.168.56.13:5244/ # 服务器地址，例如：http://192.168.1.105:8405/
        user: test # 用户名
        password: test # 密码
        domain:  # 访问域名，注意“/”结尾，例如：https://file.abc.com/
        base-path: /aali/ # 基础路径
        storage-path: / # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”
```

**Comment by 1171736840** [comment]
> > 好的，研究了下，可以使用了，确实是因为这个基础路径的含义不明确导致的
> 
> 请问你是怎么配置的，我的alist挂载了阿里网盘，虽然请求不报错但是上传有问题，文件并未正常上传，下面是我的配置文件
> 
> ```
>       - platform: webdav-2 # 存储平台标识
>         enable-storage: true  # 启用存储
>         server: http://192.168.56.13:5244/ # 服务器地址，例如：http://192.168.1.105:8405/
>         user: test # 用户名
>         password: test # 密码
>         domain:  # 访问域名，注意“/”结尾，例如：https://file.abc.com/
>         base-path: /aali/ # 基础路径
>         storage-path: / # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”
> ```

你先试试第三方 webdav 能不能正常上传

**Comment by ziwindlu** [comment]
> > > 好的，研究了下，可以使用了，确实是因为这个基础路径的含义不明确导致的
> > 
> > 
> > 请问你是怎么配置的，我的alist挂载了阿里网盘，虽然请求不报错但是上传有问题，文件并未正常上传，下面是我的配置文件
> > ```
> >       - platform: webdav-2 # 存储平台标识
> >         enable-storage: true  # 启用存储
> >         server: http://192.168.56.13:5244/ # 服务器地址，例如：http://192.168.1.105:8405/
> >         user: test # 用户名
> >         password: test # 密码
> >         domain:  # 访问域名，注意“/”结尾，例如：https://file.abc.com/
> >         base-path: /aali/ # 基础路径
> >         storage-path: / # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”
> > ```
> 
> 你先试试第三方 webdav 能不能正常上传

我第三方的webdav路径是ip:port/dav,我在配置文件中配置这个路径会报错。将ip:port/dav拆分到server和base-path时不会报错但是会上传不成功

以下是拆分后的alist日志
```
[GIN] 2023/07/03 - 17:34:57 | 200 |      48.542µs |    192.168.56.1 | HEAD     "/aali/"
[GIN] 2023/07/03 - 17:34:57 | 200 |      69.083µs |    192.168.56.1 | PUT      "/aali/64a29641cfe87b99034a4688.png"
[GIN] 2023/07/03 - 17:35:08 | 200 |     118.699µs |    192.168.56.1 | POST     "/api/fs/list"
[GIN] 2023/07/03 - 17:35:09 | 200 |      193.06µs |    192.168.56.1 | POST     "/api/fs/list"
[GIN] 2023/07/03 - 17:35:11 | 200 |  180.289587ms |    192.168.56.1 | POST     "/api/fs/list"
```
拆分前的日志
```
[GIN] 2023/07/03 - 17:36:45 | 401 |      19.347µs |    192.168.56.1 | HEAD     "/dav/aali/"
[GIN] 2023/07/03 - 17:36:45 | 401 |     332.431µs |    192.168.56.1 | HEAD     "/dav/aali/"
[GIN] 2023/07/03 - 17:36:45 | 401 |        5.37µs |    192.168.56.1 | DELETE   "/dav/aali/64a296adcfe8e1ad18a32fcb.png"
[GIN] 2023/07/03 - 17:36:45 | 401 |     200.115µs |    192.168.56.1 | DELETE   "/dav/aali/64a296adcfe8e1ad18a32fcb.png"
```

**Comment by 1171736840** [comment]
> ip:port/dav

你试试 ip:port/dav/ 在后面多加一个斜杠

**Comment by ziwindlu** [comment]
> > ip:port/dav
> 
> 你试试 ip:port/dav/ 在后面多加一个斜杠

我几乎穷举了所有可能的配置，目前而言只有配置成下面这样才能够正常发请求，但是文件并没有成功上传。我认为是alist版本与XSFS不兼容导致的

```
        server: http://192.168.56.13:5244/
        base-path: dav/aali/ # base-path有没有前缀/是不影响的
```
我的alist版本是
```
 ./alist version
Built At: 2023-06-17 12:49:43 +0000
Go Version: go1.20.5 linux/amd64
Author: Xhofe <i@nn.ci>
Commit ID: f7baec2
Version: v3.19.0
WebVersion: 3.19.0
```

下面是我用XSFS发送请求时alist的日志
```
[GIN] 2023/07/04 - 08:51:40 | 200 |      63.141µs |    192.168.56.1 | HEAD     "/webdav/"
[GIN] 2023/07/04 - 08:51:40 | 200 |      35.578µs |    192.168.56.1 | PUT      "/webdav/64a36d1ccfe815dcfb3d185b.png"
```
下面是我用alist网页端手动上传文件的alist日志
```
[GIN] 2023/07/04 - 08:53:10 | 207 |      259.89µs |    192.168.56.1 | PROPFIND  "/dav"
[GIN] 2023/07/04 - 08:53:19 | 200 |    2.632135ms |    192.168.56.1 | PUT      "/api/fs/put"
```

**Comment by yuzhi-jiang** [comment]
> > > 好的，研究了下，可以使用，确实是因为这个基础路径的暗示不明显的影响
> > 
> > 
> > 请问你是怎么配置的，我的alist挂载了阿里网盘，虽然请求不报错但是上传有问题，文件反应正常上传，下面是我的配置文件
> > ```
> >       - platform: webdav-2 # 存储平台标识
> >         enable-storage: true  # 启用存储
> >         server: http://192.168.56.13:5244/ # 服务器地址，例如：http://192.168.1.105:8405/
> >         user: test # 用户名
> >         password: test # 密码
> >         domain:  # 访问域名，注意“/”结尾，例如：https://file.abc.com/
> >         base-path: /aali/ # 基础路径
> >         storage-path: / # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”
> > ```
> 
> 你先尝试第三方webdav客户端不能正常上传

    webdav: # WebDAV
      - platform: webdav-1 # 存储平台标识
        enable-storage: true  # 启用存储
        server: http://ip:5244/ # 服务器地址，例如：http://192.168.1.105:8405/
        user: user # 用户名
        password: pass # 密码
        domain: http://ip:5244/ # 访问域名，注意“/”结尾，例如：https://file.abc.com/
        base-path: abc/minio/ # 基础路径  这里的abc和minio都是alist的文件夹路径 
        storage-path: dav/ # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”

注意：如果你使用的是alist stroage-path应该设置dav，因为这是alist的固定前缀（我印象中是的）

**Comment by ziwindlu** [comment]
> 

是的我将` storage-path: / `改为` storage-path: dav/ `就可以上传成功了，感谢。我认为说明文档中的配置说明写的有些简单了，希望作者能够将其明确一些

**Comment by ziwindlu** [comment]
> > > > 好的，研究了下，可以使用，确实是因为这个基础路径的暗示不明显的影响
> > > 
> > > 
> > > 请问你是怎么配置的，我的alist挂载了阿里网盘，虽然请求不报错但是上传有问题，文件反应正常上传，下面是我的配置文件
> > > ```
> > >       - platform: webdav-2 # 存储平台标识
> > >         enable-storage: true  # 启用存储
> > >         server: http://192.168.56.13:5244/ # 服务器地址，例如：http://192.168.1.105:8405/
> > >         user: test # 用户名
> > >         password: test # 密码
> > >         domain:  # 访问域名，注意“/”结尾，例如：https://file.abc.com/
> > >         base-path: /aali/ # 基础路径
> > >         storage-path: / # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”
> > > ```
> > 
> > 
> > 你先尝试第三方webdav客户端不能正常上传
> 
> ```
> webdav: # WebDAV
>   - platform: webdav-1 # 存储平台标识
>     enable-storage: true  # 启用存储
>     server: http://ip:5244/ # 服务器地址，例如：http://192.168.1.105:8405/
>     user: user # 用户名
>     password: pass # 密码
>     domain: http://ip:5244/ # 访问域名，注意“/”结尾，例如：https://file.abc.com/
>     base-path: abc/minio/ # 基础路径  这里的abc和minio都是alist的文件夹路径 
>     storage-path: dav/ # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”
> ```
> 
> 注意：如果你使用的是alist stroage-path应该设置dav，因为这是alist的固定前缀（我印象中是的）

是的我将storage-path: /改为storage-path: dav/就可以上传成功了，感谢。我认为说明文档中的配置说明写的有些简单了，希望作者能够将其明确一些

**Comment by 1171736840** [comment]
> > > > > 好的，研究了下，可以使用，确实是因为这个基础路径的暗示不明显的影响
> > > > 
> > > > 
> > > > 请问你是怎么配置的，我的alist挂载了阿里网盘，虽然请求不报错但是上传有问题，文件反应正常上传，下面是我的配置文件
> > > > ```
> > > >       - platform: webdav-2 # 存储平台标识
> > > >         enable-storage: true  # 启用存储
> > > >         server: http://192.168.56.13:5244/ # 服务器地址，例如：http://192.168.1.105:8405/
> > > >         user: test # 用户名
> > > >         password: test # 密码
> > > >         domain:  # 访问域名，注意“/”结尾，例如：https://file.abc.com/
> > > >         base-path: /aali/ # 基础路径
> > > >         storage-path: / # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”
> > > > ```
> > > 
> > > 
> > > 你先尝试第三方webdav客户端不能正常上传
> > 
> > 
> > ```
> > webdav: # WebDAV
> >   - platform: webdav-1 # 存储平台标识
> >     enable-storage: true  # 启用存储
> >     server: http://ip:5244/ # 服务器地址，例如：http://192.168.1.105:8405/
> >     user: user # 用户名
> >     password: pass # 密码
> >     domain: http://ip:5244/ # 访问域名，注意“/”结尾，例如：https://file.abc.com/
> >     base-path: abc/minio/ # 基础路径  这里的abc和minio都是alist的文件夹路径 
> >     storage-path: dav/ # 存储路径，可以配合 Nginx 实现访问，注意“/”结尾，默认“/”
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注意：如果你使用的是alist stroage-path应该设置dav，因为这是alist的固定前缀（我印象中是的）
> 
> 是的我将storage-path: /改为storage-path: dav/就可以上传成功了，感谢。我认为说明文档中的配置说明写的有些简单了，希望作者能够将其明确一些

好的，后续我会在新版本文档中对此情况进行详细说明

**Comment by bzw1204** [comment]
> > > ip:port/dav
> > 
> > 
> > 你试试 ip:port/dav/ 在后面多加一个斜杠
> 
> 我几乎穷举了所有可能的配置，目前而言只有配置成下面这样才能够正常发请求，但是文件并没有成功上传。我认为是alist版本与XSFS不兼容导致的
> 
> ```
>         server: http://192.168.56.13:5244/
>         base-path: /aali/ # base-path有没有前缀/是不影响的
> ```
> 
> 我的alist版本是
> 
> ```
>  ./alist version
> Built At: 2023-06-17 12:49:43 +0000
> Go Version: go1.20.5 linux/amd64
> Author: Xhofe <i@nn.ci>
> Commit ID: f7baec2
> Version: v3.19.0
> WebVersion: 3.19.0
> ```
> 
> 下面是我用XSFS发送请求时alist的日志
> 
> ```
> [GIN] 2023/07/04 - 08:51:40 | 200 |      63.141µs |    192.168.56.1 | HEAD     "/webdav/"
> [GIN] 2023/07/04 - 08:51:40 | 200 |      35.578µs |    192.168.56.1 | PUT      "/webdav/64a36d1ccfe815dcfb3d185b.png"
> ```
> 
> 下面是我用alist网页端手动上传文件的alist日志
> 
> ```
> [GIN] 2023/07/04 - 08:53:10 | 207 |      259.89µs |    192.168.56.1 | PROPFIND  "/dav"
> [GIN] 2023/07/04 - 08:53:19 | 200 |    2.632135ms |    192.168.56.1 | PUT      "/api/fs/put"
> ```

你好，请问你有使用Alist链接webdav进行下载操作吗？我这里alist配置阿里云，使用302方式无法进行下载，请问大佬有做过类似的操作及配置吗
